export const TEXT = {
	COMMON: {
		LOADING: 'Loading...',
		ERROR_PREFIX: 'Error: ',
		ERROR_DEFAULT: 'Unknown error',
	},
	HEADER: {
		FIND_YOUR_MOVIE: 'FIND YOUR MOVIE',
		SEARCH_PLACEHOLDER: 'What do you want to watch?',
		SEARCH_LABEL: '',
		SEARCH_BUTTON: 'SEARCH',
		SEARCH_ICON: '\u{1F50D}',
		ADD_MOVIE: '+ ADD MOVIE',
		LOGOUT: 'LOGOUT',
	},
	MOVIES_LIST: {
		LOADING: 'Loading movies...',
		MOVIE_FOUND_SINGULAR: 'movie found',
		MOVIE_FOUND_PLURAL: 'movies found',
		DELETE_TITLE: 'DELETE MOVIE',
		DELETE_CONFIRM: 'Are you sure you want to delete this movie?',
		CONFIRM: 'CONFIRM',
		CANCEL: 'CANCEL',
		PREV: 'PREV',
		NEXT: 'NEXT',
		PAGE_INFO: (current: number, total: number) => `Page ${current} of ${total}`,
	},
	MOVIE_TILE: {
		MENU: 'Actions',
		EDIT: 'Edit',
		DELETE: 'Delete',
		CLOSE: 'CLOSE',
		DELETE_TITLE: 'DELETE MOVIE',
		DELETE_CONFIRM: 'Are you sure you want to delete this movie?',
		CONFIRM: 'CONFIRM',
	},
	MOVIE_DETAILS: {
		NOT_FOUND: 'Movie not found',
		RATING_LABEL: 'Rating',
		DURATION_LABEL: 'Duration',
		NA: 'N/A',
		MINUTES_SUFFIX: 'min',
		RATING_SUFFIX: ' / 10',
	},
	PANEL: {
		ALL: 'ALL',
		SORT_BY: 'SORT BY',
		RELEASE_DATE: 'RELEASE DATE',
		TITLE: 'TITLE',
	},
	MOVIE_FORM: {
		TITLE_ADD: 'ADD MOVIE',
		TITLE_EDIT: 'EDIT MOVIE',
		CONGRATS: 'CONGRATULATIONS!',
		UPDATED_SUCCESS: 'The movie has been updated successfully.',
		ADDED_SUCCESS: 'The movie has been added to database successfully.',
		CLOSE: 'Close',
		ERROR_REQUIRED: 'ALL FIELDS ARE REQUIRED',
		ERROR_GENERIC: 'Something went wrong. Please try again.',
		LABEL_TITLE: 'Title',
		PLACEHOLDER_TITLE: 'Movie Title',
		LABEL_RELEASE_DATE: 'Release Date',
		PLACEHOLDER_RELEASE_DATE: 'Select Date',
		LABEL_POSTER_URL: 'Poster URL',
		PLACEHOLDER_POSTER_URL: 'https://',
		LABEL_RATING: 'Rating',
		PLACEHOLDER_RATING: '7.8',
		LABEL_GENRES: 'Genres',
		LABEL_RUNTIME: 'Runtime',
		PLACEHOLDER_RUNTIME: 'minutes',
		LABEL_OVERVIEW: 'Overview',
		PLACEHOLDER_OVERVIEW: 'Movie description',
		BUTTON_RESET: 'Reset',
		BUTTON_SUBMIT: 'Submit',
		GENRES: ['Crime', 'Documentary', 'Horror', 'Comedy', 'Fantasy', 'Adventure', 'Science Fiction', 'Action'],
	},
	USER_FORM: {
		LOGIN: 'Login',
		REGISTRATION: 'Registration',
		LABEL_NAME: 'Name',
		PLACEHOLDER_NAME: 'enter name',
		LABEL_EMAIL: 'Email',
		PLACEHOLDER_EMAIL: 'enter email',
		LABEL_PASSWORD: 'Password',
		LABEL_ADMIN: 'Admin',
		PLACEHOLDER_PASSWORD_LOGIN: 'enter password',
		PLACEHOLDER_PASSWORD_REG: 'create password',
		ERROR_NAME_REQUIRED: 'Name is required',
		ERROR_EMAIL_REQUIRED: 'Email is required',
		ERROR_PASSWORD_REQUIRED: 'Password is required',
		LINK_NO_ACCOUNT: 'Do not have an account?',
		LINK_TO_REGISTRATION: 'Go to Registration form!',
		LINK_ALREADY_REGISTERED: 'Already registered?',
		LINK_TO_LOGIN: 'Go to Login form!',
		BUTTON_RESET: 'Reset',
		BUTTON_LOGIN: 'Login',
		BUTTON_REGISTER: 'Register',
	},
	MODAL: {
		CLOSE_ICON: '\u00D7',
	},
} as const;
